from discord import Colour

categ_short: str
categ_major: str
mention_tag: str
no_tag: str
obw_color: Colour

def time(stat: str) -> str: ...
def format_stat(ctg: str, stat: str) -> str: ...
def format_role(role: Role) -> str: ...
async def delete_role(role: Role, rname: str = ...) -> None: ...
def remove_role(role: str) -> None: ...
def rename_role(before: str, after: str) -> None: ...
def generate_roles(bnet: str) -> set[str]: ...
async def update_bnet_roles(guild: Guild, disc: str, bnet: str) -> None: ...
def get_current_roles(db_roles: set[str], new_roles: set[str], disc_roles: set[str]) -> tuple[set[str], set[str]]: ...
async def update(guild: Guild, disc: str, bnet: str)-> None: ...
