class PrivateProfileError(Exception):
    _profile: str | tuple[str, str]
    def __init__(self, message: str = ..., *, profile: str | tuple[str, str] | None = ...) -> None: ...
    @property
    def profile(self) -> str | tuple[str, str]: ...

class ProfileNotFoundError(Exception):
    def __init__(self, message: str = ..., *, profile: str | tuple[str, str] | None = ...) -> None: ...
    @property
    def profile(self) -> str | tuple[str, str]: ...
