from discord.ext import commands

class BattlenetHandler(commands.Cog):
    bot: commands.Bot
    def __init__(self, bot: commands.Bot) -> None: ...
    async def account(self, ctx: commands.Context, bnet: str, platform: str) -> None: ...
    async def xbox(self, ctx: commands.Context, bnet: str) -> None: ...
    async def playstation(self, ctx: commands.Context, bnet: str) -> None: ...
    async def remove(self, ctx: commands.Context, bnet: str) -> None: ...
    async def setprimary(self, ctx: commands.Context, bnet: str) -> None: ...
    async def accounts(self, ctx: commands.Context) -> None: ...
