from discord.ext import commands
from discord_slash import SlashContext

class BattlenetHandler(commands.Cog):
    bot: commands.Bot
    def __init__(self, bot: commands.Bot) -> None: ...
    async def account(self, ctx: SlashContext, bnet: str, platform: str) -> None: ...
    async def _battlenet(self, ctx: SlashContext, bnet: str) -> None: ...
    async def xbox(self, ctx: SlashContext, xblive: str) -> None: ...
    async def playstation(self, ctx: SlashContext, psn: str) -> None: ...
    async def remove(self, ctx: SlashContext, acc: str) -> None: ...
    async def setprimary(self, ctx: SlashContext, acc: str) -> None: ...
    async def accounts(self, ctx: SlashContext) -> None: ...
