from discord.ext import commands
from discord import ApplicationContext
from discord import Bot

class BattlenetHandler(commands.Cog):
    bot: Bot
    def __init__(self, bot: Bot) -> None: ...
    async def account(self, ctx: ApplicationContext, bne: str, platform: str) -> None: ...
    async def xbox(self, ctx: ApplicationContext, xblive: str) -> None: ...
    async def playstation(self, ctx: ApplicationContext, psn: str) -> None: ...
    async def remove(self, ctx: ApplicationContext, acc: str) -> None: ...
    async def setprimary(self, ctx: ApplicationContext, acc: str) -> None: ...
    async def accounts(self, ctx: ApplicationContext) -> None: ...
    async def showroles(self, ctx: ApplicationContext) -> None: ...
    async def rank(self, ctx: ApplicationContext, bnet: str) -> None: ...
