from discord import Member, Role, Bot
from discord.ext import commands

class GenericListener(commands.Cog):
    bot: Bot
    def __init__(self, bot: Bot) -> None: ...
    async def on_error(self, event: str, *args, **kwargs) -> None: ...
    async def on_member_join(self, member: Member) -> None: ...
    async def on_guild_role_delete(self, role: Role) -> None: ...
    async def on_guild_role_update(self, before: Role, after: Role) -> None: ...
