from discord import Member, Reaction, Role, User
from discord.ext import commands
from typing import Union

class ReactionHandler(commands.Cog):
    bot: commands.Bot
    def __init__(self, bot: commands.Bot) -> None: ...
    @staticmethod
    async def on_reaction_add(reaction: Reaction, user: Union[User, Member]) -> None: ...
    @staticmethod
    async def on_member_join(member: User) -> None: ...
    @staticmethod
    async def on_guild_role_delete(role: Role) -> None: ...
    @staticmethod
    async def on_guild_role_update(before: Role, after: Role) -> None: ...
